#+TITLE: Martin Kristiansen's blog
#+AUTHOR: Martin Kristiansen
#+OPTIONS: toc:nil num:nil author:nil
#+STARTUP: nofold



This page is an example of what can be done with a simple editor and a lot of time.

Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum

* Areas of interest:
- Understanding Financial Markets
- Algorithm Design and Optimization
- Efficient Algorithm Implementation


#+BEGIN_SRC clang
  #include <stdio.h>
  int main() {
    printf("hello world\n");
    return 0;
  }
#+END_SRC
